exclude:
  patterns:
  - '*.pyc'
  - __pycache__/
  - .venv/
  - venv/
  - .git/
  - '*.egg-info/'
  - .pytest_cache/
  - .mypy_cache/
  - target/
  - node_modules/
  - dist/
  - build/
  python:
    lint_skip:
    - migrations/**
    - '*/migrations/**'
    - '*_pb2.py'
    - '*_pb2_grpc.py'
    - '*.generated.py'
    - '*_generated.py'
    test_skip:
    - conftest.py
    - '**/conftest.py'
    - test_*.py
    - '*_test.py'
    - tests/fixtures/**
    - tests/data/**
rules:
  max_file_size: 10MB
  skip_binary_files: true
  skip_generated_files: true
